### ISSUE TITLE
[bug] opensorceror/Data-Engineer-Resume-LaTeX 似乎已停止维护

### ISSUE THREAD

**Issue by LaoshuBaby** [dyweb/awesome-resume-for-chinese#11]
访问 github.com/opensorceror/Data-Engineer-Resume-LaTeX 目前已无法访问，预览图也打不开了。

![图片](https://user-images.githubusercontent.com/42690037/193424652-09a6ad2f-f89e-40c9-b2d9-ef54aa009ba3.png)

@hoochanlon 可以考虑归进deprecated里面了吧？还是需要移除它？我亲自来开这个PR可以吗？

**Comment by gaocegege** [comment]
@LaoshuBaby Sure, please help open the PR to fix it.

Thanks for your contribution! :tada: :+1:
