### ISSUE TITLE
[New Request] A LaTeX resume designed for optimal information density and aesthetic appeal.

### ISSUE THREAD

**Issue by fky2015** [dyweb/awesome-resume-for-chinese#14]
一个旨在实现最佳的信息密度和美学吸引力的 $\LaTeX$ 简历排版模板项目。

- https://github.com/fky2015/resume-ng

我也可以提供 PR；但是因为不知道应该将项目置于哪个位置，可能还需要麻烦维护者来决定。谢谢！

**Comment by gaocegege** [comment]
LGTM

放在 latex 里就好了
