### ISSUE TITLE
A hugo based resume.

### ISSUE THREAD

**Issue by laixintao** [dyweb/awesome-resume-for-chinese#3]
Preview: https://me.programmer.top/

Srouce: https://themes.3rdwavemedia.com/bootstrap-templates/resume/orbit-free-resume-cv-bootstrap-theme-for-developers/

**Comment by laixintao** [comment]
You may want to check my collections about resume here:

https://github.com/laixintao?tab=stars&utf8=%E2%9C%93&q=&q=resume

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

Can I put the screenshot of your resume in the README of this repo?

**Comment by laixintao** [comment]
Sure. : )
