### ISSUE TITLE
A minimalist resume template for Jekyll

### ISSUE THREAD

**Issue by crispgm** [dyweb/awesome-resume-for-chinese#5]
极简风格的响应式简历模板，基于 Jekyll，可以直接部署在 GitHub Pages 上。

- https://github.com/crispgm/resume
- https://crispgm.github.io/resume/resume_zh-CN.html

Thanks for adding.

**Comment by gaocegege** [comment]
Really love the template, I will add it soon. Thanks for the issue

**Comment by crispgm** [comment]
@gaocegege Thanks!
