### ISSUE TITLE
关于resume项目库的改进提议

### ISSUE THREAD

**Issue by hoodiearon** [dyweb/awesome-resume-for-chinese#8]
简历模块的增加，图片也随之增加，repo存放的图片相较文本内存过大，不利于repo的轻便快捷git clone或是download到本地

对此的提议：

* 采用图床的方式，能优化库存储图片占用（内存）过高的问题
  *  [postimages](https://postimages.org)、[sm.ms](https://sm.ms) 或是GitHub内部图床

ps： 我想加入到你的MOOC & Open Source 组

**Comment by gaocegege** [comment]
谢谢你的建议，目前我们组已经是名存实亡了 XD

我暂时先把你加为了这一个 repo 的 maintainer，如果你对其他项目感兴趣也可以跟我联系

https://github.com/dyweb/awesome-resume-for-chinese/invitations
